### ISSUE TITLE
As a guest user, when I visit the home page, I see all the stores

### ISSUE THREAD

**Issue by jxandery** [mihir787/the_pivot#1]

**Comment by jxandery** [comment]
- can click link/image of a business and customer is redirected to the individual store page

**Comment by tessgriffin** [comment]
As a guest user,

And I visit the home/landing page,

I expect to see all of the stores.

**Comment by tessgriffin** [comment]
As a guest user,

And I visit the home page,

I expect to see all of the stores listed.

**Comment by tessgriffin** [comment]
add ability to see stores
