### ISSUE TITLE
As a guest user, I can add multiple photos from different stores to a cart

### ISSUE THREAD

**Issue by jxandery** [mihir787/the_pivot#4]

**Comment by jxandery** [comment]
as a guest, when I checkout the website will ask me to login (via modal)

**Comment by jxandery** [comment]
at log in request, i can log in or if i don't have an account , i can click on create account link.

**Comment by jxandery** [comment]
if i am not registered, it will ask me to create an account; and then i will be asked to log in and then taken to checkout

**Comment by jxandery** [comment]
if i do have an account, i log in and am redirected to shopping cart

**Comment by mihir787** [comment]
If a photo has already been added to cart, that same photo cannot be added to the cart.  Flash a message OR grey out Add to cart button.
